let ApprovedAdmins =
    _GetWatchlist('ApprovedAdministrators')
    | project SearchKey, ApprovedType = Type
    | extend IsApproved = 1;
AzureActivity
| where CategoryValue == "Administrative"
| lookup kind=leftouter ApprovedAdmins
    on $left.Caller == $right.SearchKey
| extend AdminStatus =
    iff(IsApproved == 1, "Approved Administrator", "Not Approved")
| project
    TimeGenerated,
    Caller,
    AdminStatus,
    ApprovedType,
    OperationNameValue,
    ActivityStatusValue,
    ResourceGroup
| order by TimeGenerated desc
